public with sharing class actionFunctionClass {
 public String Text{get;set;}
 public String Text2{get;set;}
 
public actionFunctionClass (){
  // Text = 'Hello Welcome to Action Function constructor';
}
 public void callText (){
   Text = 'Hello Welcome to Action Function call Text Method';
}
public void callText2 (){
  // Text = 'Hello Welcome to Action Function call Text Method 22222222222222222';
}
}